System:
  Setup: true
    
  # Logs all monetary transactions passed through CraftConomy (NOT WORKING)
  Logging:
    Enabled: false
    
  Database:
    # Databases Supported:
    ##
    # mysql
    #  - These will attempt to connect to MySQL
    ##
    # sqlite
    #  - These will attempt to create & connect to SQLite
    Type: 'sqlite'
    
    #Modify if using MySQL
    Address: 'localhost'
    Port: 3306
    Username: 'root'
    Password: ''
    Db: 'Craftconomy'