name: Craftconomy3
main: com.greatmancode.craftconomy3.CC3BukkitLoader
version: ${version} b${BUILD_NUMBER}
author: Greatman
softdepend: [Spout]
commands:
    money:
      description: Check / Distribute currency.
    bank:
      description: Check / Distribute money on a Bank.
    craftconomy:
      description: Configuration command
    ccsetup:
      description: Setup command
    currency:
      description: Currency management command
    payday:
      description: Payday management command