name: Craftconomy3
main: com.greatmancode.craftconomy3.BukkitLoader
version: ${version} b${bamboo.buildNumber}-${bamboo.repository.revision.number}-${bamboo.repository.branch.name}
author: Greatman
commands:
    money:
      description: Check / Distribute currency.
    bank:
      description: Check / Distribute money on a Bank.
    craftconomy:
      description: Configuration command
    ccsetup:
      description: Setup command
    currency:
      description: Currency management command
    payday:
      description: Payday management command
    ccgroup:
      description: world group management command.